### ISSUE TITLE
possibility of having a firewall per user type

### ISSUE THREAD

**Issue by fidelio314** [netmeansnet/NmnMultiUserBundle#10]
Hello, is it possible to have a configuration to assign a spesific firewall to a user type?
exemple:

```
firewalls:
    # -> custom firewall for the admin area of the URL
    admin:
          <<with the routes admin/login_check etc:>>
          [......etc....]

    # defaut login area for standard users
    main:
         <<with the routes /login_check etc:>>
           [......etc....]
```

So i implemented an AdminUser and a FrontUser

can i apply to the AdminUser login / register etc the redirection and params of the admin firewall?

Idem for the FrontUser -> the main firewall?

An idea for you bundle would be to implement it through the nmn_user_discriminator_parameters for example:

```
firewalls:
      front_user:
             firewall_name: main
      admin_user:
              firewall_name: admin
```

Or can you propose another way? 
thank you
