### ISSUE TITLE
Can't register the second user

### ISSUE THREAD

**Issue by Congelli501** [netmeansnet/NmnMultiUserBundle#14]
Hi,

I set up my UserBundle with NmnMultiUserBundle and I created two user class. Registration for the first User works fine, but when I try to register the second one, I get redirected toward the first user registration form (route fos_user_registration_register) and it gives me the error "The CSRF token is invalid. Please try to resubmit the form".

I use the defaut layout and the csrf field _is_ present in my second user registration form.

I use FOSUserBundle 1.2 and NmnMultiUserBundle 1.2.

**Comment by leopro** [comment]
have you defined a different route for the second user?

**Comment by Congelli501** [comment]
Hi and thanks for your anwer.
I created a route for the form only (not to get the form data).

Here is the code / config (routing.yml):

```
back_users_register_prestataire:
    pattern:  /prestataire
    defaults: { _controller: Neo10UtilisateurBundle:Registration:prestataireRegister }
```

The Controller :

```
<?php

namespace Neo10\UtilisateurBundle\Controller;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Nmn\MultiUserBundle\Controller\RegistrationController as BaseController;

class RegistrationController extends BaseController
{
    public function prestataireRegisterAction()
    {
        $discriminator = $this->container->get('nmn_user_discriminator');
            $discriminator->setClass('Neo10\UtilisateurBundle\Entity\Prestataires');

            return parent::registerAction();
    }
}
```

The registration form :

```
<?php

namespace Neo10\UtilisateurBundle\Form;

use Symfony\Component\Form\FormBuilder;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseType;

class RegistrationPrestataireType extends BaseType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        parent::buildForm($builder, $options);

        // add your custom field
        $builder->add('groupe')
                ->add('raison_sociale')
                ->add('categorie')
                ->add('numeroTVA')
                ->add('site_web')
                ->add('actif', null, array('required' => false))
                ->add('type_prestataire')
                ->add('adresse', new FacturationType);

    }

    public function getName()
    {
        return 'neo10_utilisateur_prestaire_registration';
    }
}
```

And the config file :

``````
...
parameters:
    nmn_user_discriminator_parameters:
        classes:
            admin:
                entity: Neo10\UtilisateurBundle\Entity\AdministrateurGeneral
                registration: Neo10\UtilisateurBundle\Form\RegistrationAdminType
                profile: Neo10\UtilisateurBundle\Form\ProfileAdminType
                factory:
            prestataires:
                entity: Neo10\UtilisateurBundle\Entity\Prestataires
                registration: Neo10\UtilisateurBundle\Form\RegistrationPrestataireType
                profile: Neo10\UtilisateurBundle\Form\ProfilePrestataireType
                factory:
... ```
``````
